import 'package:flutter/material.dart';

class AppLocalizations extends ChangeNotifier {
  static final AppLocalizations _instance = AppLocalizations._();
  factory AppLocalizations() => _instance;
  AppLocalizations._();

  String _locale = 'en';
  String get locale => _locale;

  void setLocale(String code) {
    _locale = code;
    notifyListeners();
  }

  String t(String key) => (_strings[_locale]?[key]) ?? (_strings['en']?[key]) ?? key;

  static const supportedLocales = {
    'en': 'English',
    'ko': '한국어',
    'ja': '日本語',
    'zh': '中文',
    'vi': 'Tiếng Việt',
    'fr': 'Français',
    'es': 'Español',
  };

  static const Map<String, Map<String, String>> _strings = {
    // ==================== ENGLISH ====================
    'en': {
      // App
      'app_title': 'Guitar Teacher',
      'start': 'Start!',
      'next': 'Next',
      'done': 'Done',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'ok': 'OK',
      'later': 'Later',
      'rate_now': 'Rate Now',
      'close': 'Close',

      // Home
      'home_fretboard': 'Fretboard',
      'home_fretboard_sub': 'Note Memorization',
      'home_octave': 'Octave Form',
      'home_octave_sub': 'CAGED 5 Forms',
      'home_chord': 'Chord Practice',
      'home_chord_sub': 'Chord Changes',
      'home_scale': 'Scale',
      'home_scale_sub': 'Scale Practice',
      'home_tuner': 'Tuner',
      'home_tuner_sub': 'Guitar Tuning',
      'home_metronome': 'Metronome',
      'home_metronome_sub': 'BPM Practice',
      'home_record': 'Practice Log',
      'home_record_sub': 'Weekly Stats',
      'home_settings': 'Settings',
      'home_settings_sub': 'Theme / Language',

      // Rate dialog
      'rate_title': 'Enjoying Guitar Teacher? 🎸',
      'rate_body': 'If you find this app helpful,\nplease rate us!',

      // Settings
      'settings_title': 'Settings',
      'settings_display': 'Display',
      'settings_dark_mode': 'Dark Mode',
      'settings_dark_on': 'Dark theme',
      'settings_dark_off': 'Light theme',
      'settings_sound': 'Sound',
      'settings_metronome_vol': 'Metronome Volume',
      'settings_vol_system': 'Uses system volume',
      'settings_vol_low': 'Low',
      'settings_vol_medium': 'Medium',
      'settings_vol_high': 'High',
      'settings_vibration': 'Haptic Feedback',
      'settings_vibration_on': 'On',
      'settings_vibration_off': 'Off',
      'settings_vibration_desc': 'Vibrates on each metronome beat and when selecting answers. Helps you feel the rhythm without looking at the screen.',
      'settings_guitar': 'Guitar Settings',
      'settings_tuning': 'Tuning',
      'settings_tuning_standard': 'Standard (EADGBE)',
      'settings_language': 'Language',
      'settings_info': 'About',
      'settings_version': 'v1.1.0 by Endolphin Studio',
      'settings_rate': 'Rate This App',
      'settings_share': 'Share This App',

      // Fretboard trainer
      'fretboard_setup_title': 'Fretboard Setup',
      'fretboard_time': '⏱ Time per note (sec)',
      'fretboard_time_desc': 'A new note every {n} seconds',
      'fretboard_strings': '🎸 Select Strings',
      'fretboard_mode': '🎲 Mode',
      'fretboard_random': 'Random Notes',
      'fretboard_random_on': '12 notes appear randomly',
      'fretboard_random_off': 'You choose the note order',
      'fretboard_game_title': 'Fretboard Practice',
      'fretboard_score': 'Score',
      'fretboard_auto': 'Auto',
      'fretboard_find': 'Find it!',
      'fretboard_next_q': 'Next Question →',
      'fretboard_on_string': 'on String {n}',

      // Chord trainer
      'chord_setup_title': 'Chord Setup',
      'chord_difficulty': '🎯 Difficulty',
      'chord_beginner': '🟢 Beginner',
      'chord_beginner_desc': 'C, G, D, Am, Em etc. Open chords',
      'chord_intermediate': '🟡 Intermediate',
      'chord_intermediate_desc': 'F, Bb, Fmaj7 etc. Barre chords',
      'chord_advanced': '🔴 Advanced',
      'chord_advanced_desc': 'Cm7, Db9, Bm7b5 etc. Jazz chords',
      'chord_change_time': '⏱ Chord change: {n}s',
      'chord_game_title': 'Chord Practice',
      'chord_pause': '⏸ Paused',
      'chord_show_answer': 'Show Answer',
      'chord_hide_answer': 'Hide Answer',
      'chord_next': 'Next: {name}',

      // Octave trainer
      'octave_setup_title': 'Octave Form Setup',
      'octave_note_select': '🎵 Select Note (or Random)',
      'octave_random': 'Random',
      'octave_form_select': '📐 Select Forms',
      'octave_time': '⏱ Time Setting',
      'octave_game_title': 'Octave Form Practice',
      'octave_form_n': 'Form {n}',

      // Scale trainer
      'scale_setup_title': 'Scale Practice',
      'scale_root': 'Root Note',
      'scale_type': 'Scale Type',
      'scale_fret_range': 'Fret Range: {start} ~ {end}',
      'scale_practice_mode': 'Practice Mode',
      'scale_quiz_mode': 'Quiz Mode',
      'scale_quiz_title': 'Scale Quiz',
      'scale_where_is': 'Where is',
      'scale_on_string': 'on String {n}?',
      'scale_correct': '✅ Correct!',
      'scale_wrong': '❌ Wrong! Correct frets: {frets}',
      'scale_show_answer': '? Answer',
      'scale_hide_answer': 'Hide Answer',
      'scale_quiz_complete': 'Quiz Complete! 🎸',
      'scale_correct_count': '{correct} / {total} correct',
      'scale_accuracy': 'Accuracy: {pct}%',
      'scale_time': 'Time: {min}m {sec}s',

      // Practice record
      'record_title': 'Practice Record',
      'record_top': 'Top {n}%',
      'record_among': 'Among Guitar Learners This Week',
      'record_streak': '{n} Day Streak',
      'record_streak_amazing': 'Amazing dedication!',
      'record_streak_keep': 'Keep it up!',
      'record_streak_good': 'Good start!',
      'record_streak_start': 'Start practicing today!',
      'record_this_week': 'This Week',
      'record_minutes': 'Minutes',
      'record_sessions': 'Sessions',
      'record_by_category': 'By Category',
      'record_no_sessions': 'No sessions this week.\nStart practicing! 🎸',
      'record_recent': 'Recent Sessions',
      'record_fretboard': 'Fretboard',
      'record_octave': 'Octave',
      'record_chord': 'Chord',
      'record_scale': 'Scale',

      // Tuner
      'tuner_title': 'Tuner',
      'tuner_auto': 'Auto-advance',
      'tuner_listening': 'Listening...',
      'tuner_tap_start': 'Tap to start',

      // Metronome
      'metronome_title': 'Metronome',
    },

    // ==================== KOREAN ====================
    'ko': {
      'app_title': 'Guitar Teacher',
      'start': '시작!',
      'next': '다음',
      'done': '완료',
      'retry': '다시하기',
      'cancel': '취소',
      'ok': '확인',
      'later': '나중에',
      'rate_now': '평점 남기기',
      'close': '닫기',
      'home_fretboard': '프렛보드',
      'home_fretboard_sub': '음 위치 외우기',
      'home_octave': '옥타브 폼',
      'home_octave_sub': 'CAGED 5폼',
      'home_chord': '코드 연습',
      'home_chord_sub': '코드 체인지',
      'home_scale': '스케일',
      'home_scale_sub': '스케일 연습',
      'home_tuner': '튜너',
      'home_tuner_sub': '기타 튜닝',
      'home_metronome': '메트로놈',
      'home_metronome_sub': 'BPM 연습',
      'home_record': '연습 기록',
      'home_record_sub': '이번주 통계',
      'home_settings': '설정',
      'home_settings_sub': '테마/언어',
      'rate_title': 'Guitar Teacher 잘 쓰고 계신가요? 🎸',
      'rate_body': '도움이 되셨다면\n평점을 남겨주세요!',
      'settings_title': '설정',
      'settings_display': '화면',
      'settings_dark_mode': '다크 모드',
      'settings_dark_on': '어두운 화면',
      'settings_dark_off': '밝은 화면',
      'settings_sound': '소리',
      'settings_metronome_vol': '메트로놈 볼륨',
      'settings_vol_system': '시스템 볼륨 사용',
      'settings_vol_low': '낮음',
      'settings_vol_medium': '보통',
      'settings_vol_high': '높음',
      'settings_vibration': '진동 피드백',
      'settings_vibration_on': '켜짐',
      'settings_vibration_off': '꺼짐',
      'settings_vibration_desc': '메트로놈 박자와 정답 선택 시 진동합니다. 화면을 보지 않고도 리듬을 느낄 수 있습니다.',
      'settings_guitar': '기타 설정',
      'settings_tuning': '튜닝',
      'settings_tuning_standard': '표준 (EADGBE)',
      'settings_language': '언어',
      'settings_info': '정보',
      'settings_version': 'v1.1.0 by Endolphin Studio',
      'settings_rate': '앱 평점 남기기',
      'settings_share': '앱 공유하기',
      'fretboard_setup_title': '프렛보드 연습 설정',
      'fretboard_time': '⏱ 시간 설정 (초)',
      'fretboard_time_desc': '{n}초마다 새 음이 나옵니다',
      'fretboard_strings': '🎸 줄 선택',
      'fretboard_mode': '🎲 모드',
      'fretboard_random': '랜덤 음',
      'fretboard_random_on': '12음이 랜덤으로 나옵니다',
      'fretboard_random_off': '음 순서를 직접 지정합니다',
      'fretboard_game_title': '프렛보드 연습',
      'fretboard_score': '점수',
      'fretboard_auto': '자동',
      'fretboard_find': '을(를) 찾으세요!',
      'fretboard_next_q': '다음 문제 →',
      'fretboard_on_string': '{n}번줄에서',
      'chord_setup_title': '코드 연습 설정',
      'chord_difficulty': '🎯 난이도',
      'chord_beginner': '🟢 초급',
      'chord_beginner_desc': 'C, G, D, Am, Em 등 오픈코드',
      'chord_intermediate': '🟡 중급',
      'chord_intermediate_desc': 'F, Bb, Fmaj7 등 바레/하이코드',
      'chord_advanced': '🔴 고급',
      'chord_advanced_desc': 'Cm7, Db9, Bm7b5 등 재즈코드',
      'chord_change_time': '⏱ 코드 변경: {n}초',
      'chord_game_title': '코드 연습',
      'chord_pause': '⏸ 일시정지',
      'chord_show_answer': '정답 보기',
      'chord_hide_answer': '정답 숨기기',
      'chord_next': '다음: {name}',
      'octave_setup_title': '옥타브 폼 연습',
      'octave_note_select': '🎵 음 선택 (또는 랜덤)',
      'octave_random': '랜덤',
      'octave_form_select': '📐 폼 선택',
      'octave_time': '⏱ 시간 설정',
      'octave_game_title': '옥타브 폼 연습',
      'octave_form_n': '{n}번 폼',
      'scale_setup_title': '스케일 연습',
      'scale_root': '루트 음',
      'scale_type': '스케일 타입',
      'scale_fret_range': '프렛 범위: {start} ~ {end}',
      'scale_practice_mode': '연습 모드',
      'scale_quiz_mode': '퀴즈 모드',
      'scale_quiz_title': '스케일 퀴즈',
      'scale_where_is': '어디에 있을까요',
      'scale_on_string': '{n}번줄에서?',
      'scale_correct': '✅ 정답!',
      'scale_wrong': '❌ 오답! 정답 프렛: {frets}',
      'scale_show_answer': '? 정답',
      'scale_hide_answer': '정답 숨기기',
      'scale_quiz_complete': '퀴즈 완료! 🎸',
      'scale_correct_count': '{correct} / {total} 정답',
      'scale_accuracy': '정답률: {pct}%',
      'scale_time': '시간: {min}분 {sec}초',
      'record_title': '연습 기록',
      'record_top': '상위 {n}%',
      'record_among': '이번주 기타 학습자 중',
      'record_streak': '{n}일 연속 연습',
      'record_streak_amazing': '대단한 열정!',
      'record_streak_keep': '계속 화이팅!',
      'record_streak_good': '좋은 시작!',
      'record_streak_start': '오늘부터 시작하세요!',
      'record_this_week': '이번주',
      'record_minutes': '분',
      'record_sessions': '세션',
      'record_by_category': '카테고리별',
      'record_no_sessions': '이번주 연습 없음.\n연습을 시작하세요! 🎸',
      'record_recent': '최근 세션',
      'record_fretboard': '프렛보드',
      'record_octave': '옥타브',
      'record_chord': '코드',
      'record_scale': '스케일',
      'tuner_title': '튜너',
      'tuner_auto': '자동 넘김',
      'tuner_listening': '듣는 중...',
      'tuner_tap_start': '탭하여 시작',
      'metronome_title': '메트로놈',
    },

    // ==================== JAPANESE ====================
    'ja': {
      'app_title': 'Guitar Teacher',
      'start': 'スタート！',
      'next': '次へ',
      'done': '完了',
      'retry': 'やり直し',
      'cancel': 'キャンセル',
      'ok': 'OK',
      'later': '後で',
      'rate_now': '評価する',
      'home_fretboard': 'フレットボード',
      'home_fretboard_sub': '音の位置を覚える',
      'home_octave': 'オクターブ',
      'home_octave_sub': 'CAGED 5フォーム',
      'home_chord': 'コード練習',
      'home_chord_sub': 'コードチェンジ',
      'home_scale': 'スケール',
      'home_scale_sub': 'スケール練習',
      'home_tuner': 'チューナー',
      'home_tuner_sub': 'ギターチューニング',
      'home_metronome': 'メトロノーム',
      'home_metronome_sub': 'BPM練習',
      'home_record': '練習記録',
      'home_record_sub': '今週の統計',
      'home_settings': '設定',
      'home_settings_sub': 'テーマ/言語',
      'settings_title': '設定',
      'settings_display': '表示',
      'settings_dark_mode': 'ダークモード',
      'settings_sound': 'サウンド',
      'settings_vibration': '振動フィードバック',
      'settings_vibration_desc': 'メトロノームのビートや回答選択時に振動します。画面を見なくてもリズムを感じられます。',
      'settings_language': '言語',
      'settings_info': '情報',
      'settings_rate': 'アプリを評価',
      'settings_share': 'アプリを共有',
    },

    // ==================== CHINESE ====================
    'zh': {
      'app_title': 'Guitar Teacher',
      'start': '开始！',
      'next': '下一个',
      'done': '完成',
      'home_fretboard': '指板',
      'home_fretboard_sub': '记忆音符位置',
      'home_octave': '八度形式',
      'home_octave_sub': 'CAGED 5种形式',
      'home_chord': '和弦练习',
      'home_chord_sub': '和弦转换',
      'home_scale': '音阶',
      'home_scale_sub': '音阶练习',
      'home_tuner': '调音器',
      'home_tuner_sub': '吉他调音',
      'home_metronome': '节拍器',
      'home_metronome_sub': 'BPM练习',
      'home_record': '练习记录',
      'home_record_sub': '本周统计',
      'home_settings': '设置',
      'home_settings_sub': '主题/语言',
      'settings_title': '设置',
      'settings_language': '语言',
      'settings_vibration_desc': '节拍器节拍和选择答案时振动。无需看屏幕也能感受节奏。',
    },

    // ==================== VIETNAMESE ====================
    'vi': {
      'app_title': 'Guitar Teacher',
      'start': 'Bắt đầu!',
      'home_fretboard': 'Phím đàn',
      'home_fretboard_sub': 'Ghi nhớ nốt nhạc',
      'home_octave': 'Quãng tám',
      'home_octave_sub': 'CAGED 5 thế bấm',
      'home_chord': 'Hợp âm',
      'home_chord_sub': 'Chuyển hợp âm',
      'home_scale': 'Âm giai',
      'home_scale_sub': 'Luyện âm giai',
      'home_tuner': 'Máy lên dây',
      'home_tuner_sub': 'Lên dây guitar',
      'home_metronome': 'Máy đếm nhịp',
      'home_metronome_sub': 'Luyện BPM',
      'home_record': 'Nhật ký',
      'home_record_sub': 'Thống kê tuần',
      'home_settings': 'Cài đặt',
      'home_settings_sub': 'Giao diện/Ngôn ngữ',
      'settings_title': 'Cài đặt',
      'settings_language': 'Ngôn ngữ',
      'settings_vibration_desc': 'Rung khi nhịp metronome và khi chọn câu trả lời. Giúp bạn cảm nhận nhịp mà không cần nhìn màn hình.',
    },

    // ==================== FRENCH ====================
    'fr': {
      'app_title': 'Guitar Teacher',
      'start': 'Commencer !',
      'home_fretboard': 'Manche',
      'home_fretboard_sub': 'Mémoriser les notes',
      'home_octave': 'Octave',
      'home_octave_sub': 'CAGED 5 formes',
      'home_chord': 'Accords',
      'home_chord_sub': 'Changements d\'accords',
      'home_scale': 'Gammes',
      'home_scale_sub': 'Pratique des gammes',
      'home_tuner': 'Accordeur',
      'home_tuner_sub': 'Accorder la guitare',
      'home_metronome': 'Métronome',
      'home_metronome_sub': 'Pratique BPM',
      'home_record': 'Journal',
      'home_record_sub': 'Stats de la semaine',
      'home_settings': 'Paramètres',
      'home_settings_sub': 'Thème/Langue',
      'settings_title': 'Paramètres',
      'settings_language': 'Langue',
      'settings_vibration_desc': 'Vibre à chaque temps du métronome et lors de la sélection des réponses. Ressentez le rythme sans regarder l\'écran.',
    },

    // ==================== SPANISH ====================
    'es': {
      'app_title': 'Guitar Teacher',
      'start': '¡Empezar!',
      'home_fretboard': 'Diapasón',
      'home_fretboard_sub': 'Memorizar notas',
      'home_octave': 'Octava',
      'home_octave_sub': 'CAGED 5 formas',
      'home_chord': 'Acordes',
      'home_chord_sub': 'Cambios de acordes',
      'home_scale': 'Escalas',
      'home_scale_sub': 'Práctica de escalas',
      'home_tuner': 'Afinador',
      'home_tuner_sub': 'Afinar guitarra',
      'home_metronome': 'Metrónomo',
      'home_metronome_sub': 'Práctica BPM',
      'home_record': 'Registro',
      'home_record_sub': 'Estadísticas semanales',
      'home_settings': 'Ajustes',
      'home_settings_sub': 'Tema/Idioma',
      'settings_title': 'Ajustes',
      'settings_language': 'Idioma',
      'settings_vibration_desc': 'Vibra en cada tiempo del metrónomo y al seleccionar respuestas. Siente el ritmo sin mirar la pantalla.',
    },
  };
}

/// Shortcut function - use anywhere
String tr(String key) => AppLocalizations().t(key);
