import 'package:flutter/material.dart';

class AppLocalizations extends ChangeNotifier {
  static final AppLocalizations _instance = AppLocalizations._();
  factory AppLocalizations() => _instance;
  AppLocalizations._();

  String _locale = 'en';
  String get locale => _locale;

  void setLocale(String code) {
    _locale = code;
    notifyListeners();
  }

  String t(String key) => (_strings[_locale]?[key]) ?? (_strings['en']?[key]) ?? key;

  static const supportedLocales = {
    'en': 'English',
    'ko': '한국어',
    'ja': '日本語',
    'zh': '中文',
    'vi': 'Tiếng Việt',
    'fr': 'Français',
    'es': 'Español',
  };

  static const Map<String, Map<String, String>> _strings = {
    // ==================== ENGLISH ====================
    'en': {
      // App
      'app_title': 'Guitar Educator',
      'start': 'Start!',
      'next': 'Next',
      'done': 'Done',
      'retry': 'Retry',
      'cancel': 'Cancel',
      'ok': 'OK',
      'later': 'Later',
      'rate_now': 'Rate Now',
      'close': 'Close',
      'sec_unit': 's',

      // Home
      'home_fretboard': 'Fretboard',
      'home_fretboard_sub': 'Note Memorization',
      'home_octave': 'Octave Form',
      'home_octave_sub': '5 Chord Shapes (C·A·G·E·D)',
      'home_chord': 'Chord Practice',
      'home_chord_sub': 'Chord Changes',
      'home_sequence': 'Sequence',
      'home_sequence_sub': 'Custom Chord Practice',
      'home_scale': 'Scale',
      'home_scale_sub': 'Scale Practice',
      'home_box_pattern': 'Box Pattern',
      'home_box_pattern_sub': 'Position Practice',
      'home_tuner': 'Tuner',
      'home_tuner_sub': 'Guitar Tuning',
      'home_metronome': 'Metronome',
      'home_metronome_sub': 'BPM Practice',
      'home_record': 'Practice Log',
      'home_record_sub': 'Weekly Stats',
      'home_settings': 'Settings',
      'home_settings_sub': 'Theme / Language',

      // Rate dialog
      'rate_title': 'Enjoying Guitar Educator? 🎸',
      'rate_body': 'If you find this app helpful,\nplease rate us!',

      // Settings
      'settings_title': 'Settings',
      'settings_display': 'Display',
      'settings_dark_mode': 'Dark Mode',
      'settings_dark_on': 'Dark theme',
      'settings_dark_off': 'Light theme',
      'settings_sound': 'Sound',
      'settings_metronome_vol': 'Metronome Volume',
      'settings_vol_system': 'Uses system volume',
      'settings_vol_low': 'Low',
      'settings_vol_medium': 'Medium',
      'settings_vol_high': 'High',
      'settings_vibration': 'Haptic Feedback',
      'settings_vibration_on': 'On',
      'settings_vibration_off': 'Off',
      'settings_vibration_desc': 'Vibrates on each metronome beat and when selecting answers. Helps you feel the rhythm without looking at the screen.',
      'settings_reminder': 'Practice Reminder',
      'settings_daily_reminder': 'Daily Reminder',
      'settings_reminder_every_day': 'Every day at',
      'settings_reminder_time': 'Reminder Time',
      'settings_streak_notif': 'Streak Notification',
      'settings_streak_notif_desc': 'Celebrate when you hit practice streaks',
      'settings_comeback_notif': 'Comeback Reminder',
      'settings_comeback_notif_desc': 'Gentle nudge after 3 days of inactivity',
      'settings_off': 'Off',
      'settings_guitar': 'Guitar Settings',
      'settings_tuning': 'Tuning',
      'settings_tuning_standard': 'Standard (EADGBE)',
      'settings_language': 'Language',
      'settings_info': 'About',
      'settings_version': 'v1.1.0 by Endolphin Studio',
      'settings_rate': 'Rate This App',
      'settings_share': 'Share This App',
      'settings_note_system': 'Note Names',
      'settings_note_alphabet': 'Alphabet (C-D-E)',
      'settings_note_solfege': 'Solfege (Do-Re-Mi)',

      // Fretboard trainer
      'fretboard_setup_title': 'Fretboard Setup',
      'fretboard_time': '⏱ Time per note (sec)',
      'fretboard_time_desc': 'A new note every {n} seconds',
      'fretboard_strings': '🎸 Select Strings',
      'fretboard_mode': '🎲 Mode',
      'fretboard_random': 'Random Notes',
      'fretboard_random_on': '12 notes appear randomly',
      'fretboard_random_off': 'You choose the note order',
      'fretboard_game_title': 'Fretboard Practice',
      'fretboard_score': 'Score',
      'fretboard_auto': 'Auto',
      'fretboard_find': 'Find it!',
      'fretboard_next_q': 'Next Question →',
      'fretboard_on_string': 'on String {n}',

      // Chord trainer
      'chord_setup_title': 'Chord Setup',
      'chord_difficulty': '🎯 Difficulty',
      'chord_beginner': '🟢 Beginner',
      'chord_beginner_desc': 'C, G, D, Am, Em etc. Open chords',
      'chord_intermediate': '🟡 Intermediate',
      'chord_intermediate_desc': 'F, Bb, Fmaj7 etc. Barre chords',
      'chord_advanced': '🔴 Advanced',
      'chord_advanced_desc': 'Cm7, Db9, Bm7b5 etc. Jazz chords',
      'chord_change_time': '⏱ Chord change: {n}s',
      'chord_game_title': 'Chord Practice',
      'chord_pause': '⏸ Paused',
      'chord_show_answer': 'Show Answer',
      'chord_hide_answer': 'Hide Answer',
      'chord_next': 'Next: {name}',

      // Octave trainer
      'octave_setup_title': 'Octave Form Setup',
      'octave_note_select': '🎵 Select Note (or Random)',
      'octave_random': 'Random',
      'octave_form_select': '📐 Select Forms',
      'octave_time': '⏱ Time Setting',
      'octave_game_title': 'Octave Form Practice',
      'octave_form_n': 'Form {n}',
      'octave_info_title': '5 Chord Shapes (C·A·G·E·D)',
      'octave_info_sub': 'Each form shows 2-string octave shapes',

      // Scale trainer
      'scale_setup_title': 'Scale Practice',
      'scale_root': 'Root Note',
      'scale_type': 'Scale Type',
      'scale_fret_range': 'Fret Range: {start} ~ {end}',
      'scale_practice_mode': 'Practice Mode',
      'scale_quiz_mode': 'Quiz Mode',
      'scale_quiz_title': 'Scale Quiz',
      'scale_where_is': 'Where is',
      'scale_on_string': 'on String {n}?',
      'scale_correct': '✅ Correct!',
      'scale_wrong': '❌ Wrong! Correct frets: {frets}',
      'scale_show_answer': '? Answer',
      'scale_hide_answer': 'Hide Answer',
      'scale_quiz_complete': 'Quiz Complete! 🎸',
      'scale_correct_count': '{correct} / {total} correct',
      'scale_accuracy': 'Accuracy: {pct}%',
      'scale_time': 'Time: {min}m {sec}s',

      // Practice record
      'record_title': 'Practice Record',
      'record_top': 'Top {n}%',
      'record_among': 'Among Guitar Learners This Week',
      'record_streak': '{n} Day Streak',
      'record_streak_amazing': 'Amazing dedication!',
      'record_streak_keep': 'Keep it up!',
      'record_streak_good': 'Good start!',
      'record_streak_start': 'Start practicing today!',
      'record_this_week': 'This Week',
      'record_minutes': 'Minutes',
      'record_sessions': 'Sessions',
      'record_by_category': 'By Category',
      'record_no_sessions': 'No sessions this week.\nStart practicing! 🎸',
      'record_recent': 'Recent Sessions',
      'record_fretboard': 'Fretboard',
      'record_octave': 'Octave',
      'record_chord': 'Chord',
      'record_scale': 'Scale',

      // Tuner
      'tuner_title': 'Tuner',
      'tuner_auto': 'Auto-advance',
      'tuner_listening': 'Listening...',
      'tuner_tap_start': 'Tap to start',

      // Metronome
      'metronome_title': 'Metronome',

      // Chord Sequence
      'seq_title': 'Chord Sequence',
      'seq_pick_chord': 'Pick a Chord',
      'seq_search_chord': 'Search chord...',
      'seq_beats': 'beats',
      'seq_beat': 'Beat',
      'seq_drag_bpm': 'Drag up/down to adjust',
      'seq_add_chord': 'Add Chord',
      'seq_empty': 'Tap + to add chords',
      'seq_hint': 'Tap: change chord · Double tap: edit beats · Long press: remove',
      'seq_save_favorite': 'Save as Favorite',
      'seq_preset_name': 'Preset name',
      'seq_saved': 'Saved',
      'seq_no_favorites': 'No favorites yet',
      'seq_favorites': 'Favorites',
      'save': 'Save',
      'stop': 'Stop',
    },

    // ==================== KOREAN ====================
    'ko': {
      'app_title': 'Guitar Educator',
      'start': '시작!',
      'next': '다음',
      'done': '완료',
      'retry': '다시하기',
      'cancel': '취소',
      'ok': '확인',
      'later': '나중에',
      'rate_now': '평점 남기기',
      'close': '닫기',
      'sec_unit': '초',
      'home_fretboard': '프렛보드',
      'home_fretboard_sub': '음 위치 외우기',
      'home_octave': '옥타브 폼',
      'home_octave_sub': '코드 폼 5가지 익히기 (C·A·G·E·D)',
      'home_chord': '코드 연습',
      'home_chord_sub': '코드 체인지',
      'home_sequence': '시퀀스',
      'home_sequence_sub': '코드 연습 커스텀',
      'home_scale': '스케일',
      'home_scale_sub': '스케일 연습',
      'home_box_pattern': '박스 패턴',
      'home_box_pattern_sub': '포지션 연습',
      'home_tuner': '튜너',
      'home_tuner_sub': '기타 튜닝',
      'home_metronome': '메트로놈',
      'home_metronome_sub': 'BPM 연습',
      'home_record': '연습 기록',
      'home_record_sub': '이번주 통계',
      'home_settings': '설정',
      'home_settings_sub': '테마/언어',
      'rate_title': 'Guitar Educator 잘 쓰고 계신가요? 🎸',
      'rate_body': '도움이 되셨다면\n평점을 남겨주세요!',
      'settings_title': '설정',
      'settings_display': '화면',
      'settings_dark_mode': '다크 모드',
      'settings_dark_on': '어두운 화면',
      'settings_dark_off': '밝은 화면',
      'settings_sound': '소리',
      'settings_metronome_vol': '메트로놈 볼륨',
      'settings_vol_system': '시스템 볼륨 사용',
      'settings_vol_low': '낮음',
      'settings_vol_medium': '보통',
      'settings_vol_high': '높음',
      'settings_vibration': '진동 피드백',
      'settings_vibration_on': '켜짐',
      'settings_vibration_off': '꺼짐',
      'settings_vibration_desc': '메트로놈 박자와 정답 선택 시 진동합니다. 화면을 보지 않고도 리듬을 느낄 수 있습니다.',
      'settings_reminder': '연습 리마인더',
      'settings_daily_reminder': '매일 알림',
      'settings_reminder_every_day': '매일',
      'settings_reminder_time': '알림 시간',
      'settings_streak_notif': '연속 연습 알림',
      'settings_streak_notif_desc': '연속 연습 달성 시 축하 알림',
      'settings_comeback_notif': '복귀 알림',
      'settings_comeback_notif_desc': '3일 이상 미접속 시 부드러운 리마인더',
      'settings_off': '끄기',
      'settings_guitar': '기타 설정',
      'settings_tuning': '튜닝',
      'settings_tuning_standard': '표준 (EADGBE)',
      'settings_language': '언어',
      'settings_info': '정보',
      'settings_version': 'v1.1.0 by Endolphin Studio',
      'settings_rate': '앱 평점 남기기',
      'settings_share': '앱 공유하기',
      'settings_note_system': '음표 표기',
      'settings_note_alphabet': '알파벳 (C-D-E)',
      'settings_note_solfege': '도레미 (Do-Re-Mi)',
      'fretboard_setup_title': '프렛보드 연습 설정',
      'fretboard_time': '⏱ 시간 설정 (초)',
      'fretboard_time_desc': '{n}초마다 새 음이 나옵니다',
      'fretboard_strings': '🎸 줄 선택',
      'fretboard_mode': '🎲 모드',
      'fretboard_random': '랜덤 음',
      'fretboard_random_on': '12음이 랜덤으로 나옵니다',
      'fretboard_random_off': '음 순서를 직접 지정합니다',
      'fretboard_game_title': '프렛보드 연습',
      'fretboard_score': '점수',
      'fretboard_auto': '자동',
      'fretboard_find': '을(를) 찾으세요!',
      'fretboard_next_q': '다음 문제 →',
      'fretboard_on_string': '{n}번줄에서',
      'chord_setup_title': '코드 연습 설정',
      'chord_difficulty': '🎯 난이도',
      'chord_beginner': '🟢 초급',
      'chord_beginner_desc': 'C, G, D, Am, Em 등 오픈코드',
      'chord_intermediate': '🟡 중급',
      'chord_intermediate_desc': 'F, Bb, Fmaj7 등 바레/하이코드',
      'chord_advanced': '🔴 고급',
      'chord_advanced_desc': 'Cm7, Db9, Bm7b5 등 재즈코드',
      'chord_change_time': '⏱ 코드 변경: {n}초',
      'chord_game_title': '코드 연습',
      'chord_pause': '⏸ 일시정지',
      'chord_show_answer': '정답 보기',
      'chord_hide_answer': '정답 숨기기',
      'chord_next': '다음: {name}',
      'octave_setup_title': '옥타브 폼 연습',
      'octave_note_select': '🎵 음 선택 (또는 랜덤)',
      'octave_random': '랜덤',
      'octave_form_select': '📐 폼 선택',
      'octave_time': '⏱ 시간 설정',
      'octave_game_title': '옥타브 폼 연습',
      'octave_form_n': '{n}번 폼',
      'octave_info_title': '코드 폼 5가지 (C·A·G·E·D)',
      'octave_info_sub': '각 폼의 2줄 옥타브 형태를 보여줍니다',
      'scale_setup_title': '스케일 연습',
      'scale_root': '루트 음',
      'scale_type': '스케일 타입',
      'scale_fret_range': '프렛 범위: {start} ~ {end}',
      'scale_practice_mode': '연습 모드',
      'scale_quiz_mode': '퀴즈 모드',
      'scale_quiz_title': '스케일 퀴즈',
      'scale_where_is': '어디에 있을까요',
      'scale_on_string': '{n}번줄에서?',
      'scale_correct': '✅ 정답!',
      'scale_wrong': '❌ 오답! 정답 프렛: {frets}',
      'scale_show_answer': '? 정답',
      'scale_hide_answer': '정답 숨기기',
      'scale_quiz_complete': '퀴즈 완료! 🎸',
      'scale_correct_count': '{correct} / {total} 정답',
      'scale_accuracy': '정답률: {pct}%',
      'scale_time': '시간: {min}분 {sec}초',
      'record_title': '연습 기록',
      'record_top': '상위 {n}%',
      'record_among': '이번주 기타 학습자 중',
      'record_streak': '{n}일 연속 연습',
      'record_streak_amazing': '대단한 열정!',
      'record_streak_keep': '계속 화이팅!',
      'record_streak_good': '좋은 시작!',
      'record_streak_start': '오늘부터 시작하세요!',
      'record_this_week': '이번주',
      'record_minutes': '분',
      'record_sessions': '세션',
      'record_by_category': '카테고리별',
      'record_no_sessions': '이번주 연습 없음.\n연습을 시작하세요! 🎸',
      'record_recent': '최근 세션',
      'record_fretboard': '프렛보드',
      'record_octave': '옥타브',
      'record_chord': '코드',
      'record_scale': '스케일',
      'tuner_title': '튜너',
      'tuner_auto': '자동 넘김',
      'tuner_listening': '듣는 중...',
      'tuner_tap_start': '탭하여 시작',
      'metronome_title': '메트로놈',

      // Chord Sequence
      'seq_title': '코드 시퀀스',
      'seq_pick_chord': '코드 선택',
      'seq_search_chord': '코드 검색...',
      'seq_beats': '박',
      'seq_beat': '박자',
      'seq_drag_bpm': '위아래 드래그로 조절',
      'seq_add_chord': '코드 추가',
      'seq_empty': '+ 를 눌러 코드를 추가하세요',
      'seq_hint': '탭: 코드 변경 · 더블탭: 박자 수정 · 길게 누르기: 삭제',
      'seq_save_favorite': '즐겨찾기 저장',
      'seq_preset_name': '프리셋 이름',
      'seq_saved': '저장 완료',
      'seq_no_favorites': '즐겨찾기가 없습니다',
      'seq_favorites': '즐겨찾기',
      'save': '저장',
      'stop': '정지',
    },

    // ==================== JAPANESE ====================
    'ja': {
      // App
      'app_title': 'Guitar Educator',
      'start': 'スタート！',
      'next': '次へ',
      'done': '完了',
      'retry': 'やり直し',
      'cancel': 'キャンセル',
      'ok': 'OK',
      'later': '後で',
      'rate_now': '評価する',
      'close': '閉じる',
      'sec_unit': '秒',

      // Home
      'home_fretboard': 'フレットボード',
      'home_fretboard_sub': '音の位置を覚える',
      'home_octave': 'オクターブ',
      'home_octave_sub': '5つのコードフォーム (C·A·G·E·D)',
      'home_chord': 'コード練習',
      'home_chord_sub': 'コードチェンジ',
      'home_sequence': 'シーケンス',
      'home_sequence_sub': 'カスタムコード練習',
      'home_scale': 'スケール',
      'home_scale_sub': 'スケール練習',
      'home_box_pattern': 'ボックスパターン',
      'home_box_pattern_sub': 'ポジション練習',
      'home_tuner': 'チューナー',
      'home_tuner_sub': 'ギターチューニング',
      'home_metronome': 'メトロノーム',
      'home_metronome_sub': 'BPM練習',
      'home_record': '練習記録',
      'home_record_sub': '今週の統計',
      'home_settings': '設定',
      'home_settings_sub': 'テーマ/言語',

      // Rate dialog
      'rate_title': 'Guitar Educatorを気に入りましたか？🎸',
      'rate_body': 'このアプリが役に立ったら\n評価をお願いします！',

      // Settings
      'settings_title': '設定',
      'settings_display': '表示',
      'settings_dark_mode': 'ダークモード',
      'settings_dark_on': 'ダークテーマ',
      'settings_dark_off': 'ライトテーマ',
      'settings_sound': 'サウンド',
      'settings_metronome_vol': 'メトロノーム音量',
      'settings_vol_system': 'システム音量を使用',
      'settings_vol_low': '低',
      'settings_vol_medium': '中',
      'settings_vol_high': '高',
      'settings_vibration': '振動フィードバック',
      'settings_vibration_on': 'オン',
      'settings_vibration_off': 'オフ',
      'settings_vibration_desc': 'メトロノームのビートや回答選択時に振動します。画面を見なくてもリズムを感じられます。',
      'settings_reminder': '練習リマインダー',
      'settings_daily_reminder': '毎日リマインダー',
      'settings_reminder_every_day': '毎日',
      'settings_reminder_time': 'リマインダー時間',
      'settings_streak_notif': '連続練習通知',
      'settings_streak_notif_desc': '連続練習達成時にお祝い通知',
      'settings_comeback_notif': '復帰リマインダー',
      'settings_comeback_notif_desc': '3日以上未接続で優しいリマインダー',
      'settings_off': 'オフ',
      'settings_guitar': 'ギター設定',
      'settings_tuning': 'チューニング',
      'settings_tuning_standard': 'スタンダード (EADGBE)',
      'settings_language': '言語',
      'settings_info': '情報',
      'settings_version': 'v1.1.0 by Endolphin Studio',
      'settings_rate': 'アプリを評価',
      'settings_share': 'アプリを共有',
      'settings_note_system': '音名表記',
      'settings_note_alphabet': 'アルファベット (C-D-E)',
      'settings_note_solfege': 'ドレミ (Do-Re-Mi)',

      // Fretboard trainer
      'fretboard_setup_title': 'フレットボード設定',
      'fretboard_time': '⏱ 1音あたりの時間（秒）',
      'fretboard_time_desc': '{n}秒ごとに新しい音が出ます',
      'fretboard_strings': '🎸 弦を選択',
      'fretboard_mode': '🎲 モード',
      'fretboard_random': 'ランダム',
      'fretboard_random_on': '12音がランダムに出ます',
      'fretboard_random_off': '音の順番を指定します',
      'fretboard_game_title': 'フレットボード練習',
      'fretboard_score': 'スコア',
      'fretboard_auto': '自動',
      'fretboard_find': 'を見つけよう！',
      'fretboard_next_q': '次の問題 →',
      'fretboard_on_string': '{n}弦で',

      // Chord trainer
      'chord_setup_title': 'コード練習設定',
      'chord_difficulty': '🎯 難易度',
      'chord_beginner': '🟢 初級',
      'chord_beginner_desc': 'C, G, D, Am, Em等 オープンコード',
      'chord_intermediate': '🟡 中級',
      'chord_intermediate_desc': 'F, Bb, Fmaj7等 バレーコード',
      'chord_advanced': '🔴 上級',
      'chord_advanced_desc': 'Cm7, Db9, Bm7b5等 ジャズコード',
      'chord_change_time': '⏱ コードチェンジ: {n}秒',
      'chord_game_title': 'コード練習',
      'chord_pause': '⏸ 一時停止',
      'chord_show_answer': '答えを見る',
      'chord_hide_answer': '答えを隠す',
      'chord_next': '次: {name}',

      // Octave trainer
      'octave_setup_title': 'オクターブフォーム設定',
      'octave_note_select': '🎵 音を選択（またはランダム）',
      'octave_random': 'ランダム',
      'octave_form_select': '📐 フォームを選択',
      'octave_time': '⏱ 時間設定',
      'octave_game_title': 'オクターブフォーム練習',
      'octave_form_n': 'フォーム{n}',
      'octave_info_title': '5つのコードフォーム (C·A·G·E·D)',
      'octave_info_sub': '各フォームの2弦オクターブの形を表示します',

      // Scale trainer
      'scale_setup_title': 'スケール練習',
      'scale_root': 'ルート音',
      'scale_type': 'スケールタイプ',
      'scale_fret_range': 'フレット範囲: {start} ~ {end}',
      'scale_practice_mode': '練習モード',
      'scale_quiz_mode': 'クイズモード',
      'scale_quiz_title': 'スケールクイズ',
      'scale_where_is': 'どこにある？',
      'scale_on_string': '{n}弦で？',
      'scale_correct': '✅ 正解！',
      'scale_wrong': '❌ 不正解！正しいフレット: {frets}',
      'scale_show_answer': '? 答え',
      'scale_hide_answer': '答えを隠す',
      'scale_quiz_complete': 'クイズ完了！🎸',
      'scale_correct_count': '{correct} / {total} 正解',
      'scale_accuracy': '正解率: {pct}%',
      'scale_time': '時間: {min}分{sec}秒',

      // Practice record
      'record_title': '練習記録',
      'record_top': '上位 {n}%',
      'record_among': '今週のギター学習者の中で',
      'record_streak': '{n}日連続練習',
      'record_streak_amazing': '素晴らしい情熱！',
      'record_streak_keep': 'この調子で！',
      'record_streak_good': '良いスタート！',
      'record_streak_start': '今日から始めよう！',
      'record_this_week': '今週',
      'record_minutes': '分',
      'record_sessions': 'セッション',
      'record_by_category': 'カテゴリ別',
      'record_no_sessions': '今週の練習なし。\n練習を始めよう！🎸',
      'record_recent': '最近のセッション',
      'record_fretboard': 'フレットボード',
      'record_octave': 'オクターブ',
      'record_chord': 'コード',
      'record_scale': 'スケール',

      // Tuner
      'tuner_title': 'チューナー',
      'tuner_auto': '自動送り',
      'tuner_listening': '聴いています...',
      'tuner_tap_start': 'タップして開始',

      // Metronome
      'metronome_title': 'メトロノーム',

      // Chord Sequence
      'seq_title': 'コードシーケンス',
      'seq_pick_chord': 'コードを選択',
      'seq_search_chord': 'コード検索...',
      'seq_beats': '拍',
      'seq_beat': '拍目',
      'seq_drag_bpm': '上下ドラッグで調整',
      'seq_add_chord': 'コード追加',
      'seq_empty': '+ をタップしてコードを追加',
      'seq_hint': 'タップ: コード変更 · ダブルタップ: 拍数編集 · 長押し: 削除',
      'seq_save_favorite': 'お気に入りに保存',
      'seq_preset_name': 'プリセット名',
      'seq_saved': '保存しました',
      'seq_no_favorites': 'お気に入りはまだありません',
      'seq_favorites': 'お気に入り',
      'save': '保存',
      'stop': '停止',
    },

    // ==================== CHINESE ====================
    'zh': {
      // App
      'app_title': 'Guitar Educator',
      'start': '开始！',
      'next': '下一个',
      'done': '完成',
      'retry': '重试',
      'cancel': '取消',
      'ok': '确定',
      'later': '以后再说',
      'rate_now': '立即评分',
      'close': '关闭',
      'sec_unit': '秒',

      // Home
      'home_fretboard': '指板',
      'home_fretboard_sub': '记忆音符位置',
      'home_octave': '八度形式',
      'home_octave_sub': '5种和弦指型 (C·A·G·E·D)',
      'home_chord': '和弦练习',
      'home_chord_sub': '和弦转换',
      'home_sequence': '序列',
      'home_sequence_sub': '自定义和弦练习',
      'home_scale': '音阶',
      'home_scale_sub': '音阶练习',
      'home_box_pattern': '指型模式',
      'home_box_pattern_sub': '把位练习',
      'home_tuner': '调音器',
      'home_tuner_sub': '吉他调音',
      'home_metronome': '节拍器',
      'home_metronome_sub': 'BPM练习',
      'home_record': '练习记录',
      'home_record_sub': '本周统计',
      'home_settings': '设置',
      'home_settings_sub': '主题/语言',

      // Rate dialog
      'rate_title': '喜欢 Guitar Educator 吗？🎸',
      'rate_body': '如果觉得有帮助，\n请给我们评分！',

      // Settings
      'settings_title': '设置',
      'settings_display': '显示',
      'settings_dark_mode': '深色模式',
      'settings_dark_on': '深色主题',
      'settings_dark_off': '浅色主题',
      'settings_sound': '声音',
      'settings_metronome_vol': '节拍器音量',
      'settings_vol_system': '使用系统音量',
      'settings_vol_low': '低',
      'settings_vol_medium': '中',
      'settings_vol_high': '高',
      'settings_vibration': '振动反馈',
      'settings_vibration_on': '开启',
      'settings_vibration_off': '关闭',
      'settings_vibration_desc': '节拍器节拍和选择答案时振动。无需看屏幕也能感受节奏。',
      'settings_reminder': '练习提醒',
      'settings_daily_reminder': '每日提醒',
      'settings_reminder_every_day': '每天',
      'settings_reminder_time': '提醒时间',
      'settings_streak_notif': '连续练习通知',
      'settings_streak_notif_desc': '达到连续练习里程碑时庆祝通知',
      'settings_comeback_notif': '回归提醒',
      'settings_comeback_notif_desc': '3天以上未登录时温馨提醒',
      'settings_off': '关闭',
      'settings_guitar': '吉他设置',
      'settings_tuning': '调弦',
      'settings_tuning_standard': '标准调弦 (EADGBE)',
      'settings_language': '语言',
      'settings_info': '关于',
      'settings_version': 'v1.1.0 by Endolphin Studio',
      'settings_rate': '评价此应用',
      'settings_share': '分享此应用',
      'settings_note_system': '音名显示',
      'settings_note_alphabet': '字母 (C-D-E)',
      'settings_note_solfege': '唱名 (Do-Re-Mi)',

      // Fretboard trainer
      'fretboard_setup_title': '指板练习设置',
      'fretboard_time': '⏱ 每个音的时间（秒）',
      'fretboard_time_desc': '每{n}秒出现新音符',
      'fretboard_strings': '🎸 选择琴弦',
      'fretboard_mode': '🎲 模式',
      'fretboard_random': '随机音符',
      'fretboard_random_on': '12个音符随机出现',
      'fretboard_random_off': '自定义音符顺序',
      'fretboard_game_title': '指板练习',
      'fretboard_score': '得分',
      'fretboard_auto': '自动',
      'fretboard_find': '找到它！',
      'fretboard_next_q': '下一题 →',
      'fretboard_on_string': '在第{n}弦',

      // Chord trainer
      'chord_setup_title': '和弦练习设置',
      'chord_difficulty': '🎯 难度',
      'chord_beginner': '🟢 初级',
      'chord_beginner_desc': 'C, G, D, Am, Em等 开放和弦',
      'chord_intermediate': '🟡 中级',
      'chord_intermediate_desc': 'F, Bb, Fmaj7等 横按和弦',
      'chord_advanced': '🔴 高级',
      'chord_advanced_desc': 'Cm7, Db9, Bm7b5等 爵士和弦',
      'chord_change_time': '⏱ 和弦切换: {n}秒',
      'chord_game_title': '和弦练习',
      'chord_pause': '⏸ 已暂停',
      'chord_show_answer': '显示答案',
      'chord_hide_answer': '隐藏答案',
      'chord_next': '下一个: {name}',

      // Octave trainer
      'octave_setup_title': '八度形式设置',
      'octave_note_select': '🎵 选择音符（或随机）',
      'octave_random': '随机',
      'octave_form_select': '📐 选择形式',
      'octave_time': '⏱ 时间设置',
      'octave_game_title': '八度形式练习',
      'octave_form_n': '形式{n}',
      'octave_info_title': '5种和弦指型 (C·A·G·E·D)',
      'octave_info_sub': '每种指型显示2弦八度音程形状',

      // Scale trainer
      'scale_setup_title': '音阶练习',
      'scale_root': '根音',
      'scale_type': '音阶类型',
      'scale_fret_range': '品格范围: {start} ~ {end}',
      'scale_practice_mode': '练习模式',
      'scale_quiz_mode': '测验模式',
      'scale_quiz_title': '音阶测验',
      'scale_where_is': '在哪里',
      'scale_on_string': '在第{n}弦？',
      'scale_correct': '✅ 正确！',
      'scale_wrong': '❌ 错误！正确品格: {frets}',
      'scale_show_answer': '? 答案',
      'scale_hide_answer': '隐藏答案',
      'scale_quiz_complete': '测验完成！🎸',
      'scale_correct_count': '{correct} / {total} 正确',
      'scale_accuracy': '正确率: {pct}%',
      'scale_time': '用时: {min}分{sec}秒',

      // Practice record
      'record_title': '练习记录',
      'record_top': '前 {n}%',
      'record_among': '本周吉他学习者中',
      'record_streak': '连续练习{n}天',
      'record_streak_amazing': '令人钦佩的毅力！',
      'record_streak_keep': '继续加油！',
      'record_streak_good': '良好的开始！',
      'record_streak_start': '今天开始练习吧！',
      'record_this_week': '本周',
      'record_minutes': '分钟',
      'record_sessions': '次练习',
      'record_by_category': '按类别',
      'record_no_sessions': '本周暂无练习。\n开始练习吧！🎸',
      'record_recent': '最近的练习',
      'record_fretboard': '指板',
      'record_octave': '八度',
      'record_chord': '和弦',
      'record_scale': '音阶',

      // Tuner
      'tuner_title': '调音器',
      'tuner_auto': '自动切换',
      'tuner_listening': '聆听中...',
      'tuner_tap_start': '点击开始',

      // Metronome
      'metronome_title': '节拍器',

      // Chord Sequence
      'seq_title': '和弦序列',
      'seq_pick_chord': '选择和弦',
      'seq_search_chord': '搜索和弦...',
      'seq_beats': '拍',
      'seq_beat': '拍',
      'seq_drag_bpm': '上下拖动调整',
      'seq_add_chord': '添加和弦',
      'seq_empty': '点击 + 添加和弦',
      'seq_hint': '点击: 更改和弦 · 双击: 编辑拍数 · 长按: 删除',
      'seq_save_favorite': '收藏',
      'seq_preset_name': '预设名称',
      'seq_saved': '已保存',
      'seq_no_favorites': '暂无收藏',
      'seq_favorites': '收藏夹',
      'save': '保存',
      'stop': '停止',
    },

    // ==================== VIETNAMESE ====================
    'vi': {
      // App
      'app_title': 'Guitar Educator',
      'start': 'Bắt đầu!',
      'next': 'Tiếp',
      'done': 'Xong',
      'retry': 'Thử lại',
      'cancel': 'Hủy',
      'ok': 'OK',
      'later': 'Để sau',
      'rate_now': 'Đánh giá ngay',
      'close': 'Đóng',
      'sec_unit': 'giây',

      // Home
      'home_fretboard': 'Phím đàn',
      'home_fretboard_sub': 'Ghi nhớ nốt nhạc',
      'home_octave': 'Quãng tám',
      'home_octave_sub': '5 thế bấm hợp âm (C·A·G·E·D)',
      'home_chord': 'Hợp âm',
      'home_chord_sub': 'Chuyển hợp âm',
      'home_sequence': 'Chuỗi',
      'home_sequence_sub': 'Luyện hợp âm tùy chỉnh',
      'home_scale': 'Âm giai',
      'home_scale_sub': 'Luyện âm giai',
      'home_box_pattern': 'Box Pattern',
      'home_box_pattern_sub': 'Luyện vị trí',
      'home_tuner': 'Máy lên dây',
      'home_tuner_sub': 'Lên dây guitar',
      'home_metronome': 'Máy đếm nhịp',
      'home_metronome_sub': 'Luyện BPM',
      'home_record': 'Nhật ký',
      'home_record_sub': 'Thống kê tuần',
      'home_settings': 'Cài đặt',
      'home_settings_sub': 'Giao diện/Ngôn ngữ',

      // Rate dialog
      'rate_title': 'Bạn thích Guitar Educator không? 🎸',
      'rate_body': 'Nếu thấy hữu ích,\nhãy đánh giá nhé!',

      // Settings
      'settings_title': 'Cài đặt',
      'settings_display': 'Hiển thị',
      'settings_dark_mode': 'Chế độ tối',
      'settings_dark_on': 'Giao diện tối',
      'settings_dark_off': 'Giao diện sáng',
      'settings_sound': 'Âm thanh',
      'settings_metronome_vol': 'Âm lượng metronome',
      'settings_vol_system': 'Dùng âm lượng hệ thống',
      'settings_vol_low': 'Thấp',
      'settings_vol_medium': 'Vừa',
      'settings_vol_high': 'Cao',
      'settings_vibration': 'Phản hồi rung',
      'settings_vibration_on': 'Bật',
      'settings_vibration_off': 'Tắt',
      'settings_vibration_desc': 'Rung khi nhịp metronome và khi chọn câu trả lời. Giúp bạn cảm nhận nhịp mà không cần nhìn màn hình.',
      'settings_reminder': 'Nhac nho luyen tap',
      'settings_daily_reminder': 'Nhac nho hang ngay',
      'settings_reminder_every_day': 'Hang ngay luc',
      'settings_reminder_time': 'Thoi gian nhac nho',
      'settings_streak_notif': 'Thong bao chuoi luyen tap',
      'settings_streak_notif_desc': 'Chuc mung khi dat moc luyen tap lien tuc',
      'settings_comeback_notif': 'Nhac nho quay lai',
      'settings_comeback_notif_desc': 'Nhac nhe sau 3 ngay khong hoat dong',
      'settings_off': 'Tat',
      'settings_guitar': 'Cài đặt guitar',
      'settings_tuning': 'Lên dây',
      'settings_tuning_standard': 'Tiêu chuẩn (EADGBE)',
      'settings_language': 'Ngôn ngữ',
      'settings_info': 'Giới thiệu',
      'settings_version': 'v1.1.0 by Endolphin Studio',
      'settings_rate': 'Đánh giá ứng dụng',
      'settings_share': 'Chia sẻ ứng dụng',
      'settings_note_system': 'Ký hiệu nốt nhạc',
      'settings_note_alphabet': 'Bảng chữ cái (C-D-E)',
      'settings_note_solfege': 'Xướng âm (Do-Re-Mi)',

      // Fretboard trainer
      'fretboard_setup_title': 'Thiết lập phím đàn',
      'fretboard_time': '⏱ Thời gian mỗi nốt (giây)',
      'fretboard_time_desc': 'Nốt mới mỗi {n} giây',
      'fretboard_strings': '🎸 Chọn dây',
      'fretboard_mode': '🎲 Chế độ',
      'fretboard_random': 'Nốt ngẫu nhiên',
      'fretboard_random_on': '12 nốt xuất hiện ngẫu nhiên',
      'fretboard_random_off': 'Bạn chọn thứ tự nốt',
      'fretboard_game_title': 'Luyện phím đàn',
      'fretboard_score': 'Điểm',
      'fretboard_auto': 'Tự động',
      'fretboard_find': 'Tìm nốt!',
      'fretboard_next_q': 'Câu tiếp →',
      'fretboard_on_string': 'trên dây {n}',

      // Chord trainer
      'chord_setup_title': 'Thiết lập hợp âm',
      'chord_difficulty': '🎯 Độ khó',
      'chord_beginner': '🟢 Cơ bản',
      'chord_beginner_desc': 'C, G, D, Am, Em... Hợp âm mở',
      'chord_intermediate': '🟡 Trung bình',
      'chord_intermediate_desc': 'F, Bb, Fmaj7... Hợp âm barré',
      'chord_advanced': '🔴 Nâng cao',
      'chord_advanced_desc': 'Cm7, Db9, Bm7b5... Hợp âm jazz',
      'chord_change_time': '⏱ Chuyển hợp âm: {n}s',
      'chord_game_title': 'Luyện hợp âm',
      'chord_pause': '⏸ Tạm dừng',
      'chord_show_answer': 'Xem đáp án',
      'chord_hide_answer': 'Ẩn đáp án',
      'chord_next': 'Tiếp: {name}',

      // Octave trainer
      'octave_setup_title': 'Thiết lập quãng tám',
      'octave_note_select': '🎵 Chọn nốt (hoặc ngẫu nhiên)',
      'octave_random': 'Ngẫu nhiên',
      'octave_form_select': '📐 Chọn thế bấm',
      'octave_time': '⏱ Cài đặt thời gian',
      'octave_game_title': 'Luyện quãng tám',
      'octave_form_n': 'Thế {n}',
      'octave_info_title': '5 thế bấm hợp âm (C·A·G·E·D)',
      'octave_info_sub': 'Mỗi thế hiển thị hình dạng quãng tám 2 dây',

      // Scale trainer
      'scale_setup_title': 'Luyện âm giai',
      'scale_root': 'Nốt gốc',
      'scale_type': 'Loại âm giai',
      'scale_fret_range': 'Phạm vi phím: {start} ~ {end}',
      'scale_practice_mode': 'Chế độ luyện',
      'scale_quiz_mode': 'Chế độ kiểm tra',
      'scale_quiz_title': 'Kiểm tra âm giai',
      'scale_where_is': 'Ở đâu',
      'scale_on_string': 'trên dây {n}?',
      'scale_correct': '✅ Đúng!',
      'scale_wrong': '❌ Sai! Phím đúng: {frets}',
      'scale_show_answer': '? Đáp án',
      'scale_hide_answer': 'Ẩn đáp án',
      'scale_quiz_complete': 'Hoàn thành! 🎸',
      'scale_correct_count': '{correct} / {total} đúng',
      'scale_accuracy': 'Tỷ lệ đúng: {pct}%',
      'scale_time': 'Thời gian: {min}p {sec}s',

      // Practice record
      'record_title': 'Nhật ký luyện tập',
      'record_top': 'Top {n}%',
      'record_among': 'Trong số người học guitar tuần này',
      'record_streak': 'Luyện {n} ngày liên tiếp',
      'record_streak_amazing': 'Thật tuyệt vời!',
      'record_streak_keep': 'Tiếp tục phát huy!',
      'record_streak_good': 'Khởi đầu tốt!',
      'record_streak_start': 'Bắt đầu luyện hôm nay!',
      'record_this_week': 'Tuần này',
      'record_minutes': 'Phút',
      'record_sessions': 'Buổi tập',
      'record_by_category': 'Theo loại',
      'record_no_sessions': 'Chưa luyện tuần này.\nBắt đầu nào! 🎸',
      'record_recent': 'Gần đây',
      'record_fretboard': 'Phím đàn',
      'record_octave': 'Quãng tám',
      'record_chord': 'Hợp âm',
      'record_scale': 'Âm giai',

      // Tuner
      'tuner_title': 'Máy lên dây',
      'tuner_auto': 'Tự chuyển dây',
      'tuner_listening': 'Đang nghe...',
      'tuner_tap_start': 'Nhấn để bắt đầu',

      // Metronome
      'metronome_title': 'Máy đếm nhịp',

      // Chord Sequence
      'seq_title': 'Chuỗi hợp âm',
      'seq_pick_chord': 'Chọn hợp âm',
      'seq_search_chord': 'Tìm hợp âm...',
      'seq_beats': 'nhịp',
      'seq_beat': 'Nhịp',
      'seq_drag_bpm': 'Kéo lên/xuống để điều chỉnh',
      'seq_add_chord': 'Thêm hợp âm',
      'seq_empty': 'Nhấn + để thêm hợp âm',
      'seq_hint': 'Chạm: đổi hợp âm · Nhấn đúp: sửa nhịp · Giữ lâu: xóa',
      'seq_save_favorite': 'Lưu yêu thích',
      'seq_preset_name': 'Tên preset',
      'seq_saved': 'Đã lưu',
      'seq_no_favorites': 'Chưa có yêu thích',
      'seq_favorites': 'Yêu thích',
      'save': 'Lưu',
      'stop': 'Dừng',
    },

    // ==================== FRENCH ====================
    'fr': {
      // App
      'app_title': 'Guitar Educator',
      'start': 'Commencer !',
      'next': 'Suivant',
      'done': 'Terminé',
      'retry': 'Réessayer',
      'cancel': 'Annuler',
      'ok': 'OK',
      'later': 'Plus tard',
      'rate_now': 'Noter maintenant',
      'close': 'Fermer',
      'sec_unit': 's',

      // Home
      'home_fretboard': 'Manche',
      'home_fretboard_sub': 'Mémoriser les notes',
      'home_octave': 'Octave',
      'home_octave_sub': '5 formes d\'accords (C·A·G·E·D)',
      'home_chord': 'Accords',
      'home_chord_sub': 'Changements d\'accords',
      'home_sequence': 'Séquence',
      'home_sequence_sub': 'Pratique d\'accords perso',
      'home_scale': 'Gammes',
      'home_scale_sub': 'Pratique des gammes',
      'home_box_pattern': 'Box Pattern',
      'home_box_pattern_sub': 'Pratique de position',
      'home_tuner': 'Accordeur',
      'home_tuner_sub': 'Accorder la guitare',
      'home_metronome': 'Métronome',
      'home_metronome_sub': 'Pratique BPM',
      'home_record': 'Journal',
      'home_record_sub': 'Stats de la semaine',
      'home_settings': 'Paramètres',
      'home_settings_sub': 'Thème/Langue',

      // Rate dialog
      'rate_title': 'Vous aimez Guitar Educator ? 🎸',
      'rate_body': 'Si cette appli vous est utile,\nlaissez un avis !',

      // Settings
      'settings_title': 'Paramètres',
      'settings_display': 'Affichage',
      'settings_dark_mode': 'Mode sombre',
      'settings_dark_on': 'Thème sombre',
      'settings_dark_off': 'Thème clair',
      'settings_sound': 'Son',
      'settings_metronome_vol': 'Volume du métronome',
      'settings_vol_system': 'Volume système',
      'settings_vol_low': 'Bas',
      'settings_vol_medium': 'Moyen',
      'settings_vol_high': 'Élevé',
      'settings_vibration': 'Retour haptique',
      'settings_vibration_on': 'Activé',
      'settings_vibration_off': 'Désactivé',
      'settings_vibration_desc': 'Vibre à chaque temps du métronome et lors de la sélection des réponses. Ressentez le rythme sans regarder l\'écran.',
      'settings_reminder': 'Rappel de pratique',
      'settings_daily_reminder': 'Rappel quotidien',
      'settings_reminder_every_day': 'Chaque jour a',
      'settings_reminder_time': 'Heure du rappel',
      'settings_streak_notif': 'Notification de serie',
      'settings_streak_notif_desc': 'Celebrer les series de pratique consecutives',
      'settings_comeback_notif': 'Rappel de retour',
      'settings_comeback_notif_desc': 'Rappel doux apres 3 jours d\'inactivite',
      'settings_off': 'Desactive',
      'settings_guitar': 'Réglages guitare',
      'settings_tuning': 'Accordage',
      'settings_tuning_standard': 'Standard (EADGBE)',
      'settings_language': 'Langue',
      'settings_info': 'À propos',
      'settings_version': 'v1.1.0 by Endolphin Studio',
      'settings_rate': 'Noter l\'application',
      'settings_share': 'Partager l\'application',
      'settings_note_system': 'Notation des notes',
      'settings_note_alphabet': 'Lettres (C-D-E)',
      'settings_note_solfege': 'Solfege (Do-Re-Mi)',

      // Fretboard trainer
      'fretboard_setup_title': 'Configuration du manche',
      'fretboard_time': '⏱ Temps par note (sec)',
      'fretboard_time_desc': 'Nouvelle note toutes les {n} secondes',
      'fretboard_strings': '🎸 Cordes',
      'fretboard_mode': '🎲 Mode',
      'fretboard_random': 'Notes aléatoires',
      'fretboard_random_on': '12 notes aléatoires',
      'fretboard_random_off': 'Ordre personnalisé',
      'fretboard_game_title': 'Pratique du manche',
      'fretboard_score': 'Score',
      'fretboard_auto': 'Auto',
      'fretboard_find': 'Trouvez !',
      'fretboard_next_q': 'Question suivante →',
      'fretboard_on_string': 'sur la corde {n}',

      // Chord trainer
      'chord_setup_title': 'Configuration des accords',
      'chord_difficulty': '🎯 Difficulté',
      'chord_beginner': '🟢 Débutant',
      'chord_beginner_desc': 'C, G, D, Am, Em... Accords ouverts',
      'chord_intermediate': '🟡 Intermédiaire',
      'chord_intermediate_desc': 'F, Bb, Fmaj7... Accords barrés',
      'chord_advanced': '🔴 Avancé',
      'chord_advanced_desc': 'Cm7, Db9, Bm7b5... Accords jazz',
      'chord_change_time': '⏱ Changement : {n}s',
      'chord_game_title': 'Pratique des accords',
      'chord_pause': '⏸ Pause',
      'chord_show_answer': 'Voir la réponse',
      'chord_hide_answer': 'Masquer la réponse',
      'chord_next': 'Suivant : {name}',

      // Octave trainer
      'octave_setup_title': 'Configuration des octaves',
      'octave_note_select': '🎵 Choisir une note (ou aléatoire)',
      'octave_random': 'Aléatoire',
      'octave_form_select': '📐 Choisir les formes',
      'octave_time': '⏱ Réglage du temps',
      'octave_game_title': 'Pratique des octaves',
      'octave_form_n': 'Forme {n}',
      'octave_info_title': '5 formes d\'accords (C·A·G·E·D)',
      'octave_info_sub': 'Chaque forme montre les octaves sur 2 cordes',

      // Scale trainer
      'scale_setup_title': 'Pratique des gammes',
      'scale_root': 'Note fondamentale',
      'scale_type': 'Type de gamme',
      'scale_fret_range': 'Frettes : {start} ~ {end}',
      'scale_practice_mode': 'Mode pratique',
      'scale_quiz_mode': 'Mode quiz',
      'scale_quiz_title': 'Quiz gammes',
      'scale_where_is': 'Où se trouve',
      'scale_on_string': 'sur la corde {n} ?',
      'scale_correct': '✅ Correct !',
      'scale_wrong': '❌ Faux ! Frettes correctes : {frets}',
      'scale_show_answer': '? Réponse',
      'scale_hide_answer': 'Masquer la réponse',
      'scale_quiz_complete': 'Quiz terminé ! 🎸',
      'scale_correct_count': '{correct} / {total} correct',
      'scale_accuracy': 'Précision : {pct}%',
      'scale_time': 'Temps : {min}m {sec}s',

      // Practice record
      'record_title': 'Journal de pratique',
      'record_top': 'Top {n}%',
      'record_among': 'Parmi les guitaristes cette semaine',
      'record_streak': '{n} jours consécutifs',
      'record_streak_amazing': 'Quelle persévérance !',
      'record_streak_keep': 'Continuez ainsi !',
      'record_streak_good': 'Bon début !',
      'record_streak_start': 'Commencez aujourd\'hui !',
      'record_this_week': 'Cette semaine',
      'record_minutes': 'Minutes',
      'record_sessions': 'Séances',
      'record_by_category': 'Par catégorie',
      'record_no_sessions': 'Aucune séance cette semaine.\nCommencez à pratiquer ! 🎸',
      'record_recent': 'Séances récentes',
      'record_fretboard': 'Manche',
      'record_octave': 'Octave',
      'record_chord': 'Accord',
      'record_scale': 'Gamme',

      // Tuner
      'tuner_title': 'Accordeur',
      'tuner_auto': 'Avance auto',
      'tuner_listening': 'Écoute en cours...',
      'tuner_tap_start': 'Appuyez pour commencer',

      // Metronome
      'metronome_title': 'Métronome',

      // Chord Sequence
      'seq_title': 'Séquence d\'accords',
      'seq_pick_chord': 'Choisir un accord',
      'seq_search_chord': 'Rechercher un accord...',
      'seq_beats': 'temps',
      'seq_beat': 'Temps',
      'seq_drag_bpm': 'Glisser pour ajuster',
      'seq_add_chord': 'Ajouter un accord',
      'seq_empty': 'Appuyez sur + pour ajouter des accords',
      'seq_hint': 'Tap: changer · Double tap: modifier les temps · Appui long: supprimer',
      'seq_save_favorite': 'Sauvegarder en favori',
      'seq_preset_name': 'Nom du preset',
      'seq_saved': 'Sauvegardé',
      'seq_no_favorites': 'Aucun favori',
      'seq_favorites': 'Favoris',
      'save': 'Sauvegarder',
      'stop': 'Arrêter',
    },

    // ==================== SPANISH ====================
    'es': {
      // App
      'app_title': 'Guitar Educator',
      'start': '¡Empezar!',
      'next': 'Siguiente',
      'done': 'Hecho',
      'retry': 'Reintentar',
      'cancel': 'Cancelar',
      'ok': 'OK',
      'later': 'Más tarde',
      'rate_now': 'Valorar ahora',
      'close': 'Cerrar',
      'sec_unit': 's',

      // Home
      'home_fretboard': 'Diapasón',
      'home_fretboard_sub': 'Memorizar notas',
      'home_octave': 'Octava',
      'home_octave_sub': '5 formas de acordes (C·A·G·E·D)',
      'home_chord': 'Acordes',
      'home_chord_sub': 'Cambios de acordes',
      'home_sequence': 'Secuencia',
      'home_sequence_sub': 'Práctica de acordes personal',
      'home_scale': 'Escalas',
      'home_scale_sub': 'Práctica de escalas',
      'home_box_pattern': 'Box Pattern',
      'home_box_pattern_sub': 'Práctica de posición',
      'home_tuner': 'Afinador',
      'home_tuner_sub': 'Afinar guitarra',
      'home_metronome': 'Metrónomo',
      'home_metronome_sub': 'Práctica BPM',
      'home_record': 'Registro',
      'home_record_sub': 'Estadísticas semanales',
      'home_settings': 'Ajustes',
      'home_settings_sub': 'Tema/Idioma',

      // Rate dialog
      'rate_title': '¿Te gusta Guitar Educator? 🎸',
      'rate_body': 'Si te resulta útil,\n¡déjanos una valoración!',

      // Settings
      'settings_title': 'Ajustes',
      'settings_display': 'Pantalla',
      'settings_dark_mode': 'Modo oscuro',
      'settings_dark_on': 'Tema oscuro',
      'settings_dark_off': 'Tema claro',
      'settings_sound': 'Sonido',
      'settings_metronome_vol': 'Volumen del metrónomo',
      'settings_vol_system': 'Volumen del sistema',
      'settings_vol_low': 'Bajo',
      'settings_vol_medium': 'Medio',
      'settings_vol_high': 'Alto',
      'settings_vibration': 'Vibración',
      'settings_vibration_on': 'Activada',
      'settings_vibration_off': 'Desactivada',
      'settings_vibration_desc': 'Vibra en cada tiempo del metrónomo y al seleccionar respuestas. Siente el ritmo sin mirar la pantalla.',
      'settings_reminder': 'Recordatorio de practica',
      'settings_daily_reminder': 'Recordatorio diario',
      'settings_reminder_every_day': 'Todos los dias a las',
      'settings_reminder_time': 'Hora del recordatorio',
      'settings_streak_notif': 'Notificacion de racha',
      'settings_streak_notif_desc': 'Celebrar rachas de practica consecutivas',
      'settings_comeback_notif': 'Recordatorio de regreso',
      'settings_comeback_notif_desc': 'Recordatorio suave tras 3 dias de inactividad',
      'settings_off': 'Desactivado',
      'settings_guitar': 'Ajustes de guitarra',
      'settings_tuning': 'Afinación',
      'settings_tuning_standard': 'Estándar (EADGBE)',
      'settings_language': 'Idioma',
      'settings_info': 'Acerca de',
      'settings_version': 'v1.1.0 by Endolphin Studio',
      'settings_rate': 'Valorar la app',
      'settings_share': 'Compartir la app',
      'settings_note_system': 'Notacion de notas',
      'settings_note_alphabet': 'Letras (C-D-E)',
      'settings_note_solfege': 'Solfeo (Do-Re-Mi)',

      // Fretboard trainer
      'fretboard_setup_title': 'Configurar diapasón',
      'fretboard_time': '⏱ Tiempo por nota (seg)',
      'fretboard_time_desc': 'Nueva nota cada {n} segundos',
      'fretboard_strings': '🎸 Seleccionar cuerdas',
      'fretboard_mode': '🎲 Modo',
      'fretboard_random': 'Notas aleatorias',
      'fretboard_random_on': '12 notas aleatorias',
      'fretboard_random_off': 'Elige el orden de notas',
      'fretboard_game_title': 'Práctica del diapasón',
      'fretboard_score': 'Puntuación',
      'fretboard_auto': 'Auto',
      'fretboard_find': '¡Encuéntrala!',
      'fretboard_next_q': 'Siguiente pregunta →',
      'fretboard_on_string': 'en la cuerda {n}',

      // Chord trainer
      'chord_setup_title': 'Configurar acordes',
      'chord_difficulty': '🎯 Dificultad',
      'chord_beginner': '🟢 Principiante',
      'chord_beginner_desc': 'C, G, D, Am, Em... Acordes abiertos',
      'chord_intermediate': '🟡 Intermedio',
      'chord_intermediate_desc': 'F, Bb, Fmaj7... Acordes con cejilla',
      'chord_advanced': '🔴 Avanzado',
      'chord_advanced_desc': 'Cm7, Db9, Bm7b5... Acordes jazz',
      'chord_change_time': '⏱ Cambio de acorde: {n}s',
      'chord_game_title': 'Práctica de acordes',
      'chord_pause': '⏸ Pausado',
      'chord_show_answer': 'Ver respuesta',
      'chord_hide_answer': 'Ocultar respuesta',
      'chord_next': 'Siguiente: {name}',

      // Octave trainer
      'octave_setup_title': 'Configurar octavas',
      'octave_note_select': '🎵 Seleccionar nota (o aleatorio)',
      'octave_random': 'Aleatorio',
      'octave_form_select': '📐 Seleccionar formas',
      'octave_time': '⏱ Ajuste de tiempo',
      'octave_game_title': 'Práctica de octavas',
      'octave_form_n': 'Forma {n}',
      'octave_info_title': '5 formas de acordes (C·A·G·E·D)',
      'octave_info_sub': 'Cada forma muestra octavas en 2 cuerdas',

      // Scale trainer
      'scale_setup_title': 'Práctica de escalas',
      'scale_root': 'Nota raíz',
      'scale_type': 'Tipo de escala',
      'scale_fret_range': 'Trastes: {start} ~ {end}',
      'scale_practice_mode': 'Modo práctica',
      'scale_quiz_mode': 'Modo quiz',
      'scale_quiz_title': 'Quiz de escalas',
      'scale_where_is': 'Dónde está',
      'scale_on_string': '¿en la cuerda {n}?',
      'scale_correct': '✅ ¡Correcto!',
      'scale_wrong': '❌ ¡Incorrecto! Trastes correctos: {frets}',
      'scale_show_answer': '? Respuesta',
      'scale_hide_answer': 'Ocultar respuesta',
      'scale_quiz_complete': '¡Quiz completado! 🎸',
      'scale_correct_count': '{correct} / {total} correctas',
      'scale_accuracy': 'Precisión: {pct}%',
      'scale_time': 'Tiempo: {min}m {sec}s',

      // Practice record
      'record_title': 'Registro de práctica',
      'record_top': 'Top {n}%',
      'record_among': 'Entre guitarristas esta semana',
      'record_streak': '{n} días seguidos',
      'record_streak_amazing': '¡Increíble dedicación!',
      'record_streak_keep': '¡Sigue así!',
      'record_streak_good': '¡Buen comienzo!',
      'record_streak_start': '¡Empieza a practicar hoy!',
      'record_this_week': 'Esta semana',
      'record_minutes': 'Minutos',
      'record_sessions': 'Sesiones',
      'record_by_category': 'Por categoría',
      'record_no_sessions': 'Sin sesiones esta semana.\n¡A practicar! 🎸',
      'record_recent': 'Sesiones recientes',
      'record_fretboard': 'Diapasón',
      'record_octave': 'Octava',
      'record_chord': 'Acorde',
      'record_scale': 'Escala',

      // Tuner
      'tuner_title': 'Afinador',
      'tuner_auto': 'Avance automático',
      'tuner_listening': 'Escuchando...',
      'tuner_tap_start': 'Toca para empezar',

      // Metronome
      'metronome_title': 'Metrónomo',

      // Chord Sequence
      'seq_title': 'Secuencia de acordes',
      'seq_pick_chord': 'Elegir acorde',
      'seq_search_chord': 'Buscar acorde...',
      'seq_beats': 'tiempos',
      'seq_beat': 'Tiempo',
      'seq_drag_bpm': 'Desliza para ajustar',
      'seq_add_chord': 'Agregar acorde',
      'seq_empty': 'Toca + para agregar acordes',
      'seq_hint': 'Toca: cambiar · Doble toque: editar tiempos · Mantener: eliminar',
      'seq_save_favorite': 'Guardar como favorito',
      'seq_preset_name': 'Nombre del preset',
      'seq_saved': 'Guardado',
      'seq_no_favorites': 'Sin favoritos',
      'seq_favorites': 'Favoritos',
      'save': 'Guardar',
      'stop': 'Detener',
    },
  };
}

/// Shortcut function - use anywhere
String tr(String key) => AppLocalizations().t(key);
